### PR TITLE
Create Windows.Forensics.Jumplists.CustomDestinations_JLECmd

### PR DESCRIPTION
**Pull request by orhan-emre**
- This artifact executes Eric Zimmerman's JLECmd to parse CUSTOMDESTINATIONS-MS files in C:\ drive recursively and return output for analysis. (jlecmd.exe -d C:/ --csvf -csv tmpdir results_CustomDestinations.csv).
- JLECmd.zip can be uploaded to Velociraptor Server in order to copy it to the clients in case there is no internet connection.
- Created using @carlos_cajigas LECmd VQL as a quide.  
- JLECmd is a CLI tool for analyzing Custom Destinations jump list data. Learn more - https://github.com/EricZimmerman/JLECmd

### CODE REVIEW

**Comment by mgreen27** [comment]
Is this a duplicate of https://github.com/Velocidex/velociraptor-docs/pull/792
If so I will close this one

**Comment by orhan-emre** [comment]
> Is this a duplicate of #792 If so I will close this one

It is not duplicate. They are different 792 is for AUTOMATICDESTINATIONS-MS files and 793 is for CUSTOMDESTINATIONS-MS files. The tool used for these artifact are the same but the output files parsed and reported are different.

**Comment by scudette** [comment]
Then please combine them into the same artifact with two sources

**Comment by orhan-emre** [comment]
> Then please combine them into the same artifact with two sources

I have added additional query into the 792 in order to merge 792 and 793.

**Comment by orhan-emre** [comment]
merged with 792.

**Pull request closed without merging**
