### PR TITLE
[#748] DetectRaptor.yaml - add user-agent to API request

### PR DESCRIPTION
**Pull request by ekt0-syn**
The "velociraptor" user-agent is specified, but maybe you would like a more generic user agent or something specified as a parameter.

### CODE REVIEW

**Comment by scudette** [comment]
This option was only added in 0.7.1 so it might break if people collect this on older clients. Is it really necessary?

**Comment by ekt0-syn** [comment]
Ok. It seems necessary if people want to import DetectRaptor pack. I saw that there is a `headers` optional argument in `http_client()`, maybe we could specify a User agent directly in it? Or was it also added in 0.7.1?

**Comment by scudette** [comment]
Yeah headers might work as a workaround - but I think this was a regression in 0.7.1 which cleared the useragent completely if not set.

**Comment by mgreen27** [comment]
I just fixed this in another PR and didnt see this one. ```headers=dict(`User-Agent`="Velociraptor - DetectRaptor")``` works in my test version but after reading mikes comment above we might need to test on 0.7.1

edit - im running the RC of 0.7.1 so it works

**Pull request merged**
