### PR TITLE
Create RemoteIconForcedAuth.yaml

### PR DESCRIPTION
**Pull request by acedef**

### CODE REVIEW

**Comment by scudette** [comment]
Is this likely to work when running as system? Normally we don't see the usual shares when running at this level

**Comment by acedef** [comment]
> Is this likely to work when running as system? Normally we don't see the usual shares when running at this level

It has been working for me in a lab environment w/ the Velociraptor service. Is there another way I should test configuration-wise?

**Comment by scudette** [comment]
No it's fine. It's just that previously we found that trying to access remote shares as system just would not work because the system process can not offer any credentials to be able to access the share.

Are these public share or do they require creds?

**Comment by acedef** [comment]
Oh I see. This is enumerating share paths on the host itself. So it would have to run on the actual file server. Just trying to cut down on the load a little.

**Comment by scudette** [comment]
Oh I understand sorry. I thought this was reaching out to remote shares.

**Comment by acedef** [comment]
No worries. Good to know for the future.

**Comment by mgreen27** [comment]
FYI - I already added a powershell less wmi method to the exchange here: https://docs.velociraptor.app/exchange/artifacts/pages/shares/

**Pull request merged**
