### PR TITLE
Add a server notebook template for viewing recent flows

### PR DESCRIPTION
**Pull request by misje**
This notebook is handy for getting an overview of recently scheduled flows/collections, either for auditing reasons or just as a handy way to find a recent collection.

### CODE REVIEW

**Comment by misje** [comment]
Probably blocked by #879.

**Comment by misje** [comment]
I have run the import, verified that the zip contains this artifact, but it does not show up in velociraptor. No errors either.

**Comment by misje** [comment]
Is there perhaps some missing logic needed for imports of notebook artifacts, since this is a new feature and this is the first of its kind?

**Comment by scudette** [comment]
It should be there?

**Comment by misje** [comment]
It's not listed in Results either.

**Comment by scudette** [comment]
I was able to import it manually and after removing the exchange prefix

**Pull request merged**
